//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHealthMessaging.Els.Service
{
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class LookupClient : System.ServiceModel.ClientBase<ILookup>, ILookup
    {
        
        public LookupClient()
        {
        }
        
        public LookupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public LookupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LookupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public LookupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ListInteractionsResponse ILookup.ListInteractions(ListInteractionsRequest request)
        {
            return Channel.ListInteractions(request);
        }
        
        public InteractionType[] ListInteractions(ListInteractions listInteractions1)
        {
            var inValue = new ListInteractionsRequest {listInteractions = listInteractions1};
            var retVal = ((ILookup)(this)).ListInteractions(inValue);
            return retVal.listInteractionsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidateInteractionResponse1 ILookup.ValidateInteraction(ValidateInteractionRequest request)
        {
            return Channel.ValidateInteraction(request);
        }
        
        public ValidateInteractionResponse ValidateInteraction(ValidateInteraction validateInteraction1)
        {
            var inValue = new ValidateInteractionRequest {validateInteraction = validateInteraction1};
            var retVal = ((ILookup)(this)).ValidateInteraction(inValue);
            return retVal.validateInteractionResponse;
        }
    }
}
